### ISSUE TITLE
Support Grinder

### ISSUE THREAD

**Issue by donny-dont** [dogma-dart/dogma-codegen#12]
Currently Dogma Codegen uses [build_system](https://pub.dartlang.org/packages/build_system) for incremental builds. It may be useful to support users of Grinder directly.

The use of build_system was meant to follow along with [source_gen](https://pub.dartlang.org/packages/source_gen) but Grinder may be a better solution.

**Comment by donny-dont** [comment]
Currently not planned but if there's enough interest I can get around to it. Feel free to vote with :+1: or :-1:

**Comment by kasperpeulen** [comment]
:+1:

**Comment by kasperpeulen** [comment]
For the people wanting to get dogma to work with grinder, you can define your tasks like this:

``` dart
import 'package:grinder/grinder.dart';
import 'package:dogma_codegen/build.dart';
import 'package:watcher/watcher.dart';

void main(List<String> args) {
  grind(args);
}

@Task('build dogma')
Future buildDogma() async {
  await build([],
      convertPath: 'lib/convert',
      modelPath: 'lib/models',
      mapper: false,
      unmodifiable: false);
    // or whatever defaults you want of course
}

@Task('watch dogma')
Future watchDogma() async {
  await buildDogma();

  print('Watching changes');

  await for (var _ in new Watcher('lib/models').events) {
    final sw = new Stopwatch()..start();
    await buildDogma();
    print('build finished [${sw.elapsedMilliseconds} ms]\n');
  }
}
```

**Comment by donny-dont** [comment]
The latest bit of code is using the `build` library. This looks like it will be the standard way of doing code generation going forward as its being supported by Google. Closing this as it will handle watching and building so grinder is not needed and will likely not be recommended going forward.
